# Generated by Django 4.1.1 on 2022-09-28 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_auto_20210415_0854'),
        ('meetups', '0005_meetup_date_meetup_organizer_email'),
    ]

    operations = [
    ]
